
CREATE SEQUENCE SEQ_CLIENTES;
CREATE SEQUENCE SEQ_PRODUTOS;
CREATE SEQUENCE SEQ_VENDAS;
CREATE SEQUENCE SEQ_VENDAS_NUMERO;
CREATE SEQUENCE SEQ_VENDAS_ITENS;
CREATE SEQUENCE SEQ_LOG_INTEGRACAO;

SET TERM ^ ;

CREATE OR ALTER TRIGGER TBI_CLIENTES FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_CLIENTES;
END^

CREATE OR ALTER TRIGGER TBU_CLIENTES FOR CLIENTES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.DT_ALTERACAO = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TBI_PRODUTOS FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_PRODUTOS;
END^

CREATE OR ALTER TRIGGER TBU_PRODUTOS FOR PRODUTOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.DT_ALTERACAO = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TBI_VENDAS FOR VENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_VENDAS;
    IF (NEW.NUMERO IS NULL) THEN
        NEW.NUMERO = NEXT VALUE FOR SEQ_VENDAS_NUMERO;
END^

CREATE OR ALTER TRIGGER TBU_VENDAS FOR VENDAS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.DT_ALTERACAO = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TBI_VENDAS_ITENS FOR VENDAS_ITENS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_VENDAS_ITENS;
END^

CREATE OR ALTER TRIGGER TBI_LOG_INTEGRACAO FOR LOG_INTEGRACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_LOG_INTEGRACAO;
END^

SET TERM ; ^

