/* ============================================================================
   ERP VENDAS - Indices secundarios
   ============================================================================ */

SET NAMES UTF8;
CONNECT 'C:\CartSys\DB\ERP_VENDAS.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

CREATE INDEX IDX_CLIENTES_NOME       ON CLIENTES (NOME);
CREATE INDEX IDX_PRODUTOS_DESCRICAO  ON PRODUTOS (DESCRICAO);
CREATE INDEX IDX_VENDAS_DT_VENDA     ON VENDAS (DT_VENDA);
CREATE INDEX IDX_VENDAS_STATUS       ON VENDAS (STATUS);
CREATE INDEX IDX_VENDAS_FIN_EXTERNO  ON VENDAS (ID_FINANCEIRO_EXTERNO);
CREATE INDEX IDX_VENDAS_ITENS_VENDA  ON VENDAS_ITENS (ID_VENDA);
CREATE INDEX IDX_LOG_DT_EVENTO       ON LOG_INTEGRACAO (DT_EVENTO);
CREATE INDEX IDX_LOG_VENDA           ON LOG_INTEGRACAO (ID_VENDA);

COMMIT WORK;
