/* ============================================================================
   ERP FINANCEIRO - Tabelas
   ============================================================================ */

SET NAMES UTF8;
CONNECT 'C:\CartSys\DB\ERP_FINANCEIRO.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

/* ----------------------------------------------------------------------------
   TITULOS - cada venda gera um titulo a receber
   ---------------------------------------------------------------------------- */
CREATE TABLE TITULOS (
    ID                  INTEGER         NOT NULL,
    ID_VENDA_EXTERNA    INTEGER         NOT NULL,
    NUMERO_VENDA        INTEGER         NOT NULL,
    ID_CLIENTE_EXTERNO  INTEGER         NOT NULL,
    NOME_CLIENTE        VARCHAR(120)    NOT NULL,
    DOC_CLIENTE         VARCHAR(20),
    EMAIL_CLIENTE       VARCHAR(120),
    VALOR               NUMERIC(15,2)   NOT NULL,
    DT_EMISSAO          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_VENCIMENTO       DATE            NOT NULL,
    DT_QUITACAO         TIMESTAMP,
    DT_CANCELAMENTO     TIMESTAMP,
    STATUS              VARCHAR(20)     DEFAULT 'PENDENTE' NOT NULL,
    FORMA_PAGAMENTO     VARCHAR(30),
    OBSERVACOES         VARCHAR(500),
    DT_CADASTRO         TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DT_ALTERACAO        TIMESTAMP,
    CONSTRAINT PK_TITULOS         PRIMARY KEY (ID),
    CONSTRAINT UQ_TITULOS_VENDA   UNIQUE (ID_VENDA_EXTERNA),
    CONSTRAINT CK_TITULOS_STATUS  CHECK (STATUS IN ('PENDENTE','QUITADO','CANCELADO')),
    CONSTRAINT CK_TITULOS_VALOR   CHECK (VALOR > 0)
);

COMMENT ON COLUMN TITULOS.ID_VENDA_EXTERNA IS 'ID da venda no ERP de Vendas (chave logica entre os modulos)';

/* ----------------------------------------------------------------------------
   MOVIMENTACOES - historico de movimentos do titulo
   ---------------------------------------------------------------------------- */
CREATE TABLE MOVIMENTACOES (
    ID                INTEGER         NOT NULL,
    ID_TITULO         INTEGER         NOT NULL,
    TIPO              VARCHAR(20)     NOT NULL,
    VALOR             NUMERIC(15,2)   NOT NULL,
    DT_MOVIMENTACAO   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    OBSERVACAO        VARCHAR(500),
    USUARIO           VARCHAR(60),
    CONSTRAINT PK_MOVIMENTACOES        PRIMARY KEY (ID),
    CONSTRAINT FK_MOVIMENTACOES_TITULO FOREIGN KEY (ID_TITULO) REFERENCES TITULOS(ID),
    CONSTRAINT CK_MOVIMENTACOES_TIPO   CHECK (TIPO IN ('EMISSAO','QUITACAO','CANCELAMENTO'))
);

/* ----------------------------------------------------------------------------
   LOG_INTEGRACAO
   ---------------------------------------------------------------------------- */
CREATE TABLE LOG_INTEGRACAO (
    ID              INTEGER       NOT NULL,
    DT_EVENTO       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TIPO            VARCHAR(30)   NOT NULL,
    DIRECAO         VARCHAR(10)   NOT NULL,
    ENDPOINT        VARCHAR(200),
    METODO_HTTP     VARCHAR(10),
    REQUEST_BODY    BLOB SUB_TYPE TEXT,
    RESPONSE_BODY   BLOB SUB_TYPE TEXT,
    STATUS_HTTP     INTEGER,
    SUCESSO         CHAR(1)       NOT NULL,
    MENSAGEM_ERRO   VARCHAR(500),
    ID_TITULO       INTEGER,
    CONSTRAINT PK_LOG_INTEGRACAO_FIN  PRIMARY KEY (ID),
    CONSTRAINT CK_LOG_FIN_DIRECAO     CHECK (DIRECAO IN ('SAIDA','ENTRADA')),
    CONSTRAINT CK_LOG_FIN_SUCESSO     CHECK (SUCESSO IN ('S','N'))
);

CREATE SEQUENCE SEQ_TITULOS;
CREATE SEQUENCE SEQ_MOVIMENTACOES;
CREATE SEQUENCE SEQ_LOG_INTEGRACAO_FIN;

SET TERM ^ ;

CREATE OR ALTER TRIGGER TBI_TITULOS FOR TITULOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_TITULOS;
END^

CREATE OR ALTER TRIGGER TBU_TITULOS FOR TITULOS
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.DT_ALTERACAO = CURRENT_TIMESTAMP;
END^

CREATE OR ALTER TRIGGER TBI_MOVIMENTACOES FOR MOVIMENTACOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_MOVIMENTACOES;
END^

CREATE OR ALTER TRIGGER TBI_LOG_INTEGRACAO_FIN FOR LOG_INTEGRACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = NEXT VALUE FOR SEQ_LOG_INTEGRACAO_FIN;
END^

SET TERM ; ^

CREATE INDEX IDX_TITULOS_STATUS    ON TITULOS (STATUS);
CREATE INDEX IDX_TITULOS_DT_VENC   ON TITULOS (DT_VENCIMENTO);
CREATE INDEX IDX_TITULOS_CLIENTE   ON TITULOS (ID_CLIENTE_EXTERNO);
CREATE INDEX IDX_MOV_TITULO        ON MOVIMENTACOES (ID_TITULO);
CREATE INDEX IDX_LOG_FIN_DT        ON LOG_INTEGRACAO (DT_EVENTO);

COMMIT WORK;
